accounts/urls.py
from django.conf.urls import url
from .views import *

app_name = 'accounts'

urlpatterns = [

    url(r'^login/$', login_view, name="login"),
    url(r'^register/$', register_view, name="register"),
    url(r'^logout/$', logout_view, name="logout"),


]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home.views import anasayfa
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', anasayfa, name="home"),
    url(r'^post/', include('post.urls')),
    url(r'^accounts/', include('accounts.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
from .views import *

app_name = 'post'

urlpatterns = [

    url(r'^$', post_index, name="default"),
    url(r'^index/$', post_index, name="index"),
    url(r'^create/$', post_create, name="create"),

    url(r'^(?P<slug>[\w-]+)/$', post_detail, name="detail"),
    url(r'^(?P<slug>[\w-]+)/update/$', post_update, name="update"),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name="delete"),

]

home/models.py
from django.db import models

# Create your models here.

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, inital-scale=1" />
    <title>{% block title %}Django Ders{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    {% include "header.html" %}
<div class="col-lg-6 col-md-offset-2">
    {% include "messages.html" %}
</div>
    {% block body %}

    {% endblock %}

<script src="{% static 'js/jquery.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>

</body>
</html>

templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-inverse navbar-fixed-top " role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home' %}" class="navbar-brand">Django Dersleri</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">

            <!-- Arama Çubuğu -->
            <form class="navbar-form navbar-left" role="search" method="GET" action="">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Arama" value="{{ request.GET.q }}" >
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Ara">
                    </span>
                </div>
            </form>

            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'post:create' %}">Yazı Ekle</a></li>
                {% endif %}
                <li><a href="{% url 'home' %}">Anasayfa</a></li>
                <li><a href="{% url 'post:default' %}">Blog</a></li>
                <li><a href="{% url 'home' %}">Hakkımda</a></li>
                <li><a href="{% url 'home' %}">İletişim</a></li>

            {% if not request.user.is_authenticated %}
                <li><a href="{% url 'accounts:register' %}">Üye Ol</a></li>
                <li><a href="{% url 'accounts:login' %}">Giriş Yap</a></li>
                {% else %}
                <li><a>Kullanıcı: {{ request.user.get_full_name }}</a></li>
                <li><a href="{% url 'accounts:logout' %}"> Çıkış Yap</a></li>
            {% endif %}
            </ul>

        </nav>

    </div>
</nav>

templates/home.html
{% extends "base.html" %}

{% block title %} Anasayfa - {{ block.super }} {% endblock %}

  {% block body %}

    <div class="container">
      <div class="row">
          <div class="col-md-8" style="background-color: #67b168;" ><h2>Merhabalar Ben Saliha</h2></div>
          <div class="col-md-8" style="background-color: #5b80b2;" ><h4>Python Django Teknolojileri ile geliştirdiğim ilk Blogum, Temel blog araçları bulunuyor.</h4></div>
          <div class="col-md-8" style="background-color: #5a7b8c;" ><h4>Sağ üstten Blog menüsüne tıklayarak yazdığım bir kaç deneme yazısına ulaşabilirsin.</h4></div>

      </div>

Hoşgeldiniz: {{ request.user.get_full_name }}

    </div>

  {% endblock %}

templates/messages.html
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
               <div class="row">
                <div class="col-md-offset-3">
                <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>{{ message }} !</strong>
                </div>
                </div>
                </div>
            {% endfor %}
        </ul>
    {% endif %}